name: OF2406

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - name: "OpenFOAM 2406"
            install: "cd ."
            compile: ./.compileOF2406.sh

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: install OF
      run: ${{ matrix.install}}
    - name: make
      run: ${{ matrix.compile}}
